name       : xcursorgen
version    : 1.0.6
release    : 1
source     :
    - http://xorg.freedesktop.org/archive/individual/app/xcursorgen-1.0.6.tar.bz2 : 31c8910f54eb175a8a74a60e7662697467e21a8bf948220a6048a93924b3f66c
license    : MIT
component  : xorg.apps
summary    : Create an X cursor file from PNG images
description: |
    xcursorgen prepares X11 cursor sets for use with libXcursor.
builddeps:
    - pkgconfig(x11)
    - pkgconfig(libpng)
    - pkgconfig(xcursor)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
